name: jest unit test

on:
  pull_request:
    paths:
      - 'assets/games/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Setup the necessary tools
      - uses: actions/checkout@v4
        with:
          fetch-depth: 64

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.2

      - name: npm login
        run:
          npm config set //registry.npmjs.org/:_authToken=$NPM_READONLY_AUTH_TOKEN
        env:
          NPM_READONLY_AUTH_TOKEN: ${{ secrets.NPM_READONLY_AUTH_TOKEN }}

      - name: npm install dependencies
        run: npm install

      - name: Run Unit Test
        run: npm test

      - name: Check Coverage Threshold
        run: |
          if [ -f "coverage/coverage-summary.json" ]; then
            COVERAGE=$(node -p "JSON.parse(require('fs').readFileSync('coverage/coverage-summary.json', 'utf8')).total.lines.pct")
            echo "Total line coverage: ${COVERAGE}%"
            if (( $(echo "$COVERAGE < 80" | bc -l) )); then
              echo "❌ Coverage is below 80% threshold. Current: ${COVERAGE}%"
              exit 1
            else
              echo "✅ Coverage meets 80% threshold. Current: ${COVERAGE}%"
            fi
          else
            echo "❌ Coverage report not found. Make sure Jest is configured to generate coverage."
            exit 1
          fi
