name: jest unit test

on:
  pull_request:
    paths:
      - 'assets/games/**'
      - 'tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      # Setup the necessary tools
      - uses: actions/checkout@v4
        with:
          # Need full history so git diff between base and head works reliably
          fetch-depth: 0

      - name: Detect code changes
        id: changes
        run: |
          echo "Comparing base ${{ github.event.pull_request.base.sha }} to head ${{ github.event.pull_request.head.sha }}"
          # Use triple-dot to compare merge base (safer for PRs)
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})
          echo "Changed files:"; printf '%s\n' "$CHANGED_FILES"

          # Match typical JS/TS source & test file extensions
          if printf '%s\n' "$CHANGED_FILES" | grep -E '\.(cjs|mjs|js|jsx|ts|tsx)$' >/dev/null 2>&1; then
            echo "code_changed=true" >> $GITHUB_OUTPUT
            echo "Code changes detected => tests will run"
          else
            echo "code_changed=false" >> $GITHUB_OUTPUT
            echo "No code (*.js|*.cjs|*.mjs|*.jsx|*.ts|*.tsx) changes detected => skipping tests"
          fi

      - name: Use Node.js
        if: steps.changes.outputs.code_changed == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 20.19.2

      - name: npm login
        if: steps.changes.outputs.code_changed == 'true'
        run:
          npm config set //registry.npmjs.org/:_authToken=$NPM_READONLY_AUTH_TOKEN
        env:
          NPM_READONLY_AUTH_TOKEN: ${{ secrets.NPM_READONLY_AUTH_TOKEN }}

      - name: npm install dependencies
        if: steps.changes.outputs.code_changed == 'true'
        run: npm install

      - name: Run Unit Test
        id: test
        if: steps.changes.outputs.code_changed == 'true'
        run: |
          # Run tests and capture output
          TEST_OUTPUT=$(npm test 2>&1)
          echo "$TEST_OUTPUT"

          # Save complete test output for PR comment
          echo "test_output<<EOF" >> $GITHUB_OUTPUT
          echo "$TEST_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Check Coverage Threshold
        if: steps.changes.outputs.code_changed == 'true'
        run: |
          # Extract line coverage percentage from Jest output
          COVERAGE=$(echo "${{ steps.test.outputs.test_output }}" | grep "All files" | awk '{print $10}' | sed 's/%//')

          if [ -z "$COVERAGE" ]; then
            echo "❌ Could not extract coverage from test output"
            exit 1
          fi

          echo "Total line coverage: ${COVERAGE}%"

          # Check if coverage meets 80% threshold
          if (( $(echo "$COVERAGE < 80" | bc -l) )); then
            echo "❌ Coverage is below 80% threshold. Current: ${COVERAGE}%"
            exit 1
          else
            echo "✅ Coverage meets 80% threshold. Current: ${COVERAGE}%"
          fi

      - name: Delete previous comment and add a new one
        if: always() && steps.changes.outputs.code_changed == 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const testOutput = `${{ steps.test.outputs.test_output }}`;

            const comments = await github.issues.listComments({
              owner,
              repo,
              issue_number
            });

            for (const comment of comments.data) {
              if (comment.body.includes('Test Coverage Report')) {
                await github.issues.deleteComment({
                  owner,
                  repo,
                  comment_id: comment.id
                });
              }
            }

            const body = `## 🧪 Test Coverage Report

            \`\`\`
            ${testOutput}
            \`\`\`
            `;

            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body: body
            });

      - name: Skip comment (no code changes)
        if: always() && steps.changes.outputs.code_changed != 'true'
        uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const body = `🧪 Jest tests skipped: no code (.ts/.js/.tsx/.jsx) changes detected in this PR.`;
            github.issues.createComment({
              issue_number,
              owner,
              repo,
              body
            });
